[context.production.environment]
  HUGO_VERSION = "0.47"

[[redirects]]
from = "/homes/*-province"
to = "/hauser/:splat-provinz"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "Guardamar"}
to = "/hauser/guardamar-del-segura/"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "guardamar"}
to = "/hauser/guardamar-del-segura/"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "Villamartin"}
to = "/hauser/villamartin/"
status = 301
force = false
[[redirects]]
from = "/search/"
query = {location = "villamartin"}
to = "/hauser/villamartin/"
status = 301
force = false
